#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill --randomize ~/Pictures/wallpapers/* &
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# make CapsLock behave like Ctrl:
setxkbmap -option ctrl:nocaps
# make short-pressed Ctrl behave like Escape:
xcape -e 'Control_L=Escape'
# Make US and PL keyboard layout togglable with Shift+Alt
setxkbmap -layout us,pl -option grp:alt_shift_toggle
# Start libinput gestures
libinput-gestures-setup autostart start
# Xinput configs (touchpad)
xinput set-prop "DLL075B:01 06CB:76AF Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL075B:01 06CB:76AF Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL075B:01 06CB:76AF Touchpad" "libinput Disable While Typing Enabled" 0
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Dunst
dunst &
# network-manager-applet
nm-applet &


# Workspaces
bspc monitor -d I II III IV V

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Look and feel
bspc config border_width         2
bspc config window_gap          10
bspc config top_padding			27
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_padding		0
bspc config border_radius		15
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
bspc config automatic_scheme	spiral
